version: '3.9'
services:
  backend:
    container_name: flask
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file: .env
    volumes:
      - .:/app
    networks:
      - trandung
networks:
  trandung: